### ISSUE TITLE
RMS auf Wellenform

### ISSUE THREAD

**Issue by bastibe** [saschabilert/browser_signal_analyzer#13]
Über den Minima/Maxima könnte man zusätzlich den RMS auf der Wellenform zeichnen.

**Comment by saschabilert** [comment]
Berechnung des RMS für jeden Block der Wellenform und neuen Canvas auf die Wellenform geplotted (auch schon in CSS eingebunden). Es gibt noch einen kleinen bug mit dem Farben wechsel.
