### ISSUE TITLE
Auf Firefox fixen

### ISSUE THREAD

**Issue by bastibe** [saschabilert/browser_signal_analyzer#24]
Auf Firefox kann man nicht zoomen

**Comment by saschabilert** [comment]
Es funktioniert eigentlich auf Firefox fast alles, aber die Darstellung und die Buttons sind nicht an der richtigen stelle. Kann eigentlich beim schön machen gefixed werden.

**Comment by bastibe** [comment]
Was im Firefox noch fehlt:

- Man kann im Spektrogramm nicht zoomen.
- Pause pausiert nur beim ersten Mal, danach stoppt es.
- Der Download-Button hat keine Funktion.
- In den Instructions überlappen sich Buttons und Text.
