### ISSUE TITLE
Redraw waveform while changing spectrogram mode

### ISSUE THREAD

**Issue by moritzbalters** [saschabilert/browser_signal_analyzer#44]
Beim Wehcsel zwischen Ansichten im Spektrogramm z.B. zwischen Pegel und Phase, wird die WEllenform unnötigerweise jedes mal neu gezeichnet

**Comment by saschabilert** [comment]
Kümmere ich mich heute noch drum (Funktion vor audioprocessing)

**Comment by saschabilert** [comment]
Mit einer drawcheck variable gelöst, ist aber nicht so schön...
