### ISSUE TITLE
Spektrogramm sollte beim Zoomen nicht verschwinden

### ISSUE THREAD

**Issue by bastibe** [saschabilert/browser_signal_analyzer#7]
Das hängt offenbar mit der maximalen Canvas-Größe zusammen. Eventuell Fehlermeldung ausgeben?

**Comment by moritzbalters** [comment]
Spectrogram size limited to div size and to maximum Canvas size for Chrome
a6d4b60c6b2350c2c6443234040f08aa9474afc5
